version: '2'
services:
  tissue_segmentation:
    image: tissue_segmentation 
    ports:
      - "5000:5000"
    build:
            context: ..
            dockerfile: dockerfiles/Dockerfile


    volumes:
            - ../:/nnUNet
            - /media:/media
            - ../models:/models
    environment:
              - nnUNet_raw=/path/to/raw
              - nnUNet_preprocessed=/path/to/preprocessed
              - nnUNet_results=/path/to/results
    working_dir: /nnUNet
    ipc: host
