version: '2'
services:
  nnunet:
    image: nnunet_image
    ports:
      - "5000:5000"
    build:
            context: ..
            dockerfile: dockerfiles/Dockerfile


    volumes:
            - ../:/nnUNet
            - /path/to/nnUNet_raw:/data/nnUNet_raw
            - ../models:/models
    environment:
            - nnUNet_raw=/path/to/nnUNet_raw
            - nnUNet_preprocessed=/path/to/nnUNet_preprocessed
            - nnUNet_results=/path/to/nnUNet_results
    working_dir: /nnUNet
    ipc: host
